import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 
  | 'en' | 'sw' | 'yo' | 'zu' | 'am' | 'ha' | 'ig' | 'so' | 'om' 
  | 'sn' | 'wo' | 'xh' | 'ti' | 'af' | 'ak' | 'rw' | 'ln' | 'ff' 
  | 'bem' | 'tn' | 'tw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Landing page
    tagline: "Cultured in Connection",
    createAccount: "Create account",
    alreadyMember: "Already a member? Log in",
    culture: "Culture",
    discover: "Discover",
    collective: "Collective",
    languages: "Languages",
    signIn: "Sign In",
    joinNow: "Join Now",
    whyCultureDifferent: "Why \"The Culture\" Is Different",
    globalCulture: "Global Culture",
    globalCultureDesc: "This is a culture inspired space. Be it friendship culture, dating culture, relationship culture and even beyond. Connect with people from all corners of the globe—find your tribe.",
    virtualDates: "Virtual Dates",
    virtualDatesDesc: "Explore new ways to connect, like cooking a dish together over video call, sharing your favorite poetry, or showing each other local art galleries.",
    sharedEvents: "Shared Events",
    sharedEventsDesc: "Attend exclusive online and offline cultural events: film festivals, music festivals, poetry slams, or even regional festivals. Meet your match while immersing yourself in art, culture, and history.",
    curatedPlaylists: "Curated Playlists",
    curatedPlaylistsDesc: "Each week, enjoy curated playlists designed around different cultural genres. Find someone to vibe with over an Afrobeat playlist or discover classical Eastern music together.",
    intellectualDialogue: "Intellectual & Creative Dialogue",
    intellectualDialogueDesc: "Engage in meaningful conversations, whether it's about philosophy, literature, or film. Our platform's focus is on building deeper emotional and intellectual connections.",
    discoverMeaningful: "Discover Meaningful Connections",
    culturalQuiz: "Cultural Compatibility Quiz",
    culturalQuizDesc: "Find out which cultural experiences resonate with your soul through a simple yet thoughtful quiz that reflects your values, interests, and artistic tastes.",
    personalizedMatch: "Personalized Matchmaking",
    personalizedMatchDesc: "Using your cultural preferences, passions, and personality traits, we match you with others who share similar lifestyles, traditions, and ideology.",
    shareConnect: "Share and Connect",
    shareConnectDesc: "Participate in engaging conversations, exchange creative works, explore unique cultural events, or enjoy a virtual dinner date with someone who speaks your cultural language.",
    memberStories: "Our Members' Stories",
    getInspired: "Get Inspired, Explore Together",
    readyExperience: "Ready to Experience a Connection Like No Other?",
    embraceCulture: "Embrace culture, art, and soul—find someone who truly gets you.",
    createProfileNow: "Create Your Profile Now",
    
    // Auth & Sign In
    back: "Back",
    welcomeBack: "Welcome back",
    email: "Email",
    password: "Password",
    location: "Location",
    confirmPassword: "Confirm Password",
    passwordMinimum: "Password (minimum 10 characters)",
    createStrongPassword: "Create a strong password",
    confirmYourPassword: "Confirm your password",
    yourPassword: "Your password",
    signingIn: "Signing In...",
    creatingAccount: "Creating Account...",
    dontHaveAccount: "Don't have an account?",
    meaningfulConnections: "Experience meaningful connections rooted in culture and heritage",
    continueJourney: "Continue your journey of meaningful connections",
    
    // Navigation
    messages: "Messages",
    liveStream: "Live Stream",
    getVerified: "Get Verified",
    premium: "Premium",
    welcome: "Welcome",
    signOut: "Sign Out",
    friends: "Friends",
    matches: "Matches",
    
    // About page
    aboutOloo: "About Òloo",
    culturedConnection: "Cultured in Connection",
    aboutDesc: "Òloo is a premium dating platform designed to celebrate African culture while fostering meaningful connections across the diaspora.",
    ourMission: "Our Mission",
    missionDesc: "We believe in bringing people together through shared values, cultural appreciation, and authentic connections. Òloo provides a safe, secure, and culturally-rich environment for individuals to find meaningful relationships.",
    whatMakesDifferent: "What Makes Us Different",
    culturalCelebration: "Cultural celebration at the heart of every connection",
    advancedVerification: "Advanced verification systems for safety and authenticity",
    premiumFeatures: "Premium features designed for meaningful relationships",
    communityFocused: "Community-focused platform with real-time connections",
    contactUs: "Contact Us",
    contactDesc: "Have questions or feedback? We'd love to hear from you at",
    
    // Premium page
    upgradeYourLoveLife: "Upgrade Your Love Life",
    premiumDesc: "Unlock premium features and find meaningful connections with people who share your cultural values",
    mostPopular: "Most Popular",
    silver: "Silver",
    gold: "Gold",
    platinum: "Platinum",
    perMonth: "/month",
    enhancedDating: "Enhanced dating experience",
    premiumCultural: "Premium cultural connections",
    eliteDating: "Elite dating experience",
    unlimitedLikes: "Unlimited likes",
    seeWhoLikedYou: "See who liked you",
    superLikesPerDay: "Super Likes per day",
    boostPerMonth: "Boost per month",
    noAds: "No ads",
    everythingInSilver: "Everything in Silver",
    unlimitedSuperLikes: "Unlimited Super Likes",
    boostsPerMonth: "Boosts per month",
    priorityLikes: "Priority likes",
    readReceipts: "Read receipts",
    culturalMatchFilter: "Cultural match filter",
    everythingInGold: "Everything in Gold",
    unlimitedBoosts: "Unlimited Boosts",
    messageBeforeMatching: "Message before matching",
    prioritySupport: "Priority customer support",
    exclusiveEvents: "Exclusive events access",
    advancedFilters: "Advanced filters",
    choose: "Choose",
    neverRunOut: "Never run out of chances to connect",
    noMoreGuessing: "No more guessing - see your admirers",
    superBoosts: "Super Boosts",
    getMoreViews: "Get 10x more profile views",
    culturalFilters: "Cultural Filters",
    findSharedHeritage: "Find matches who share your heritage",
    faq: "Frequently Asked Questions",
    canCancelAnytime: "Can I cancel anytime?",
    cancelDesc: "Yes, you can cancel your subscription at any time. No questions asked.",
    paymentsSecure: "Are payments secure?",
    paymentsSecureDesc: "Absolutely. We use industry-standard encryption to protect your payment information.",
    
    // Profile page
    profile: "Profile",
    editProfile: "Edit Profile",
    settings: "Settings",
    tokens: "Tokens",
    stats: "Stats",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    displayName: "Display Name",
    bio: "Bio",
    occupation: "Occupation",
    education: "Education",
    interests: "Interests",
    relationshipGoals: "Relationship Goals",
    age: "Age",
    verificationStatus: "Verification Status",
    accountSettings: "Account Settings",
    privacySettings: "Privacy Settings",
    notificationSettings: "Notification Settings",
    
    // Discover page
    loading: "Loading...",
    noMoreProfiles: "No more profiles",
    loadMore: "Load More",
    viewProfile: "View Profile",
    addFriend: "Add Friend",
    sendMessage: "Send Message",
    superLike: "Super Like",
    like: "Like",
    pass: "Pass",
    undo: "Undo",
    boost: "Boost",
    
    // Streaming & Video
    startStreaming: "Start Streaming",
    stopStreaming: "Stop Streaming",
    joinStream: "Join Stream",
    leaveStream: "Leave Stream",
    viewers: "Viewers",
    goLive: "Go Live",
    endStream: "End Stream",
    
    // Common UI
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    upload: "Upload",
    download: "Download",
    
    // Footer
    about: "About",
    privacyPolicy: "Privacy Policy",
    termsConditions: "Terms & Conditions",
    faqs: "FAQs",
    support: "Support",
    newsletterText: "Stay up to date with exclusive cultural events and matchmaking tips. Sign up for our newsletter",
    enterEmail: "Enter your email",
    subscribe: "Subscribe",
    footerLegalText: "By tapping 'Sign in' / 'Create account', you agree to our",
    termsOfService: "Terms of Service",
    learnDataProcessing: "Learn how we process your data in our",
    cookiesPolicy: "Cookies Policy",
    and: "and",
    
    // Onboarding
    termsOfServiceTitle: "Terms of Service",
    reviewTerms: "Please review and accept our terms",
    agreeTerms: "I agree to the Terms of Service and Privacy Policy",
    tellAboutYourself: "Tell us about yourself",
    basicInformation: "Basic information for your profile",
    username: "Username",
    enterUsername: "Enter your username",
    usernameDisplay: "Username will appear on profile",
    dateOfBirth: "Date of Birth",
    agePublicNotBirthday: "Your age will be public, but not your birthday",
    gender: "Gender",
    selectGender: "Select your gender",
    man: "Man",
    woman: "Woman",
    other: "Other",
    sexualOrientation: "Sexual Orientation",
    selectOrientation: "Select your orientation",
    straight: "Straight",
    gay: "Gay",
    lesbian: "Lesbian",
    bisexual: "Bisexual",
    pansexual: "Pansexual",
    basicInfo: "Basic Information",
    fewMoreDetails: "A few more details about you",
    height: "Height",
    selectHeight: "Select your height",
    bodyType: "Body Type",
    selectBodyType: "Select your body type",
    athletic: "Athletic",
    slim: "Slim",
    average: "Average",
    curvy: "Curvy",
    heavyset: "Heavyset",
    relationshipPreferences: "Relationship Preferences",
    whatLookingFor: "What are you looking for?",
    lookingFor: "Looking for",
    selectLookingFor: "Select what you're looking for",
    casualDating: "Casual dating",
    seriousRelationship: "Serious relationship",
    friendship: "Friendship",
    somethingCasual: "Something casual",
    longTermPartner: "Long-term partner",
    hobbies: "Hobbies & Interests",
    enterHobbies: "Enter your hobbies (comma-separated)",
    personality: "Personality Type",
    selectPersonality: "Select your personality type",
    introvert: "Introvert",
    extrovert: "Extrovert",
    ambivert: "Ambivert",
    addPhotos: "Add Photos",
    uploadYourPhotos: "Upload your best photos (up to 6)",
    dragDropPhotos: "Drag and drop photos here or click to browse",
    dragDropActivePhotos: "Drop photos here...",
    photos: "Photos",
    letsStart: "Let's Start!",
    continue: "Continue",
    savingProfile: "Saving Profile...",
    
    // Verification
    profileVerification: "Profile Verification",
    getOrangeCheckmark: "Get your orange checkmark",
    alreadyVerified: "Already Verified!",
    verifiedProfile: "Verified Profile",
    profileSuccessfullyVerified: "Your profile has been successfully verified and displays the orange checkmark.",
    increasedTrust: "Increased Trust",
    otherUsersKnowReal: "Other users know you're real",
    moreMatches: "More Matches",
    verifiedProfilesVisibility: "Verified profiles get more visibility",
    enhancedSecurity: "Enhanced Security",
    protectedFakeProfiles: "Protected against fake profiles",
    backToDating: "Back to Dating",
    getVerifiedTitle: "Get Verified",
    standOut2Step: "Stand out with our secure 2-step verification process",
    howItWorks: "How it works:",
    livenessCheck: "Liveness Check",
    followInstructionsReal: "Follow simple instructions to prove you're a real person",
    faceMatching: "Face Matching",
    compareLiveVideo: "We'll compare your live video with your profile photos",
    orangeCheckmark: "Orange Checkmark",
    verifiedBadgeAuthentic: "Get the verified badge that shows you're authentic",
    requirements: "Requirements:",
    cameraAccessVideo: "Camera access for video verification",
    goodLighting: "Good lighting conditions",
    clearProfilePhoto: "At least one clear profile photo",
    minutesTime: "2-3 minutes of your time",
    startVerification: "Start Verification",
    profileRequired: "Profile Required",
    completeProfileVerification: "Please complete your profile before verification.",
    goToProfile: "Go to Profile",
    
    // Privacy, Terms, Cookies
    privacyPolicyTitle: "Privacy Policy",
    termsOfServicePageTitle: "Terms of Service",
    cookiesPolicyTitle: "Cookies Policy",
    lastUpdated: "Last updated",
    informationWeCollect: "Information We Collect",
    howWeUseInfo: "How We Use Your Information",
    informationSharing: "Information Sharing",
    dataSecurity: "Data Security",
    yourPrivacyRights: "Your Privacy Rights",
    dataRetention: "Data Retention",
    childrensPrivacy: "Children's Privacy",
    internationalUsers: "International Users",
    changesToPolicy: "Changes to This Policy",
    contactSection: "Contact",
    acceptanceOfTerms: "Acceptance of Terms",
    eligibility: "Eligibility",
    accountSecurity: "Account Security",
    userConduct: "User Conduct",
    contentGuidelines: "Content Guidelines",
    premiumServices: "Premium Services",
    termination: "Termination",
    disclaimers: "Disclaimers",
    limitationLiability: "Limitation of Liability",
    governingLaw: "Governing Law",
    contact: "Contact",
    whatAreCookies: "What Are Cookies",
    typesOfCookies: "Types of Cookies We Use",
    thirdPartyCookies: "Third-Party Cookies",
    cookieDuration: "Cookie Duration",
    managingCookies: "Managing Cookie Preferences",
    mobileDevices: "Mobile Devices",
    updatesToPolicy: "Updates to This Policy",
    
    // NotFound
    pageNotFound: "Page not found",
    oopsPageNotFound: "Oops! Page not found",
    returnToHome: "Return to Home",
    
    // Hero Section
    premiumDating: "Premium Dating",
    redefined: "Redefined",
    culturalConnections: "Cultural Connections",
    experienceAfrocentricLuxury: "Experience Afrocentric luxury dating with vibrant cultural connections, exclusive streaming features, and meaningful relationships rooted in heritage.",
    startMatching: "Start Matching",
    watchDemo: "Watch Demo",
    culturalMembers: "Cultural Members",
    matchSuccess: "Match Success",
    liveStreamingTitle: "Live Streaming",
    premiumDatingExperience: "Premium dating experience for sophisticated connections",
  },
  sw: {
    tagline: "Tunavyounganishwa na Utamaduni",
    createAccount: "Unda akaunti",
    alreadyMember: "Tayari ni mwanachama? Ingia",
    culture: "Utamaduni",
    discover: "Gundua",
    collective: "Pamoja",
    languages: "Lugha",
    signIn: "Ingia",
    joinNow: "Jiunge Sasa",
    whyCultureDifferent: "Kwa Nini \"Utamaduni\" Ni Tofauti",
    globalCulture: "Utamaduni wa Kimataifa",
    globalCultureDesc: "Hii ni nafasi iliyochochewa na utamaduni. Iwe ni utamaduni wa urafiki, utamaduni wa mapenzi, au hata zaidi. Unganisha na watu kutoka kona zote za dunia.",
    virtualDates: "Mikutano ya Mtandaoni",
    virtualDatesDesc: "Gundua njia mpya za kuungana, kama kupika pamoja kupitia video, kushiriki mashairi yako unayoyapenda, au kuonyesha maarobaini ya sanaa za ndani.",
    sharedEvents: "Matukio ya Pamoja",
    sharedEventsDesc: "Hudhuria matukio ya kipekee ya mtandaoni na nje ya mtandao: vifungamano vya filamu, tamasha za muziki, mashindano ya mashairi.",
    curatedPlaylists: "Orodha za Kuchaguliwa",
    curatedPlaylistsDesc: "Kila wiki, furahia orodha za nyimbo zilizochaguliwa kwa makundi tofauti ya kitamaduni.",
    intellectualDialogue: "Mazungumzo ya Kiakili na Ubunifu",
    intellectualDialogueDesc: "Shiriki katika mazungumzo yenye maana, iwe ni kuhusu falsafa, fasihi, au filamu.",
    discoverMeaningful: "Gundua Uhusiano Wenye Maana",
    culturalQuiz: "Jaribio la Utangamano wa Kitamaduni",
    culturalQuizDesc: "Gundua ni uzoefu gani wa kitamaduni unaovutia roho yako kupitia jaribio rahisi lakini lenye fikra.",
    personalizedMatch: "Uoanishaji wa Kibinafsi",
    personalizedMatchDesc: "Tukitumia mapendeleo yako ya kitamaduni, shauku, na sifa za utu, tunakuunganisha na wengine wanaoshiriki maisha sawa.",
    shareConnect: "Shiriki na Unganisha",
    shareConnectDesc: "Shiriki katika mazungumzo ya kuvutia, badilishana kazi za ubunifu, gundua matukio ya kipekee ya kitamaduni.",
    memberStories: "Hadithi za Wanachama Wetu",
    getInspired: "Pata Msukumo, Gundua Pamoja",
    readyExperience: "Uko Tayari Kupata Uhusiano Tofauti?",
    embraceCulture: "Kubali utamaduni, sanaa, na roho—pata mtu anayekuelewa kweli.",
    createProfileNow: "Unda Wasifu Wako Sasa",
    back: "Rudi",
    welcomeBack: "Karibu tena",
    email: "Barua pepe",
    password: "Nenosiri",
    location: "Mahali",
    confirmPassword: "Thibitisha Nenosiri",
    passwordMinimum: "Nenosiri (angalau herufi 10)",
    createStrongPassword: "Unda nenosiri imara",
    confirmYourPassword: "Thibitisha nenosiri lako",
    yourPassword: "Nenosiri lako",
    signingIn: "Inaingia...",
    creatingAccount: "Inaunda Akaunti...",
    dontHaveAccount: "Huna akaunti?",
    meaningfulConnections: "Pata uhusiano wenye maana unaozingatia utamaduni na urithi",
    continueJourney: "Endelea safari yako ya uhusiano wenye maana",
    messages: "Ujumbe",
    liveStream: "Mباشر ya Moja kwa Moja",
    getVerified: "Thibitishwa",
    premium: "Bora",
    welcome: "Karibu",
    signOut: "Toka",
    friends: "Marafiki",
    matches: "Mechi",
    aboutOloo: "Kuhusu Òloo",
    culturedConnection: "Tunavyounganishwa na Utamaduni",
    aboutDesc: "Òloo ni jukwaa la mapenzi la hali ya juu lililobuniwa kusherehekea utamaduni wa Kiafrika.",
    ourMission: "Dhamira Yetu",
    missionDesc: "Tunaamini katika kuwaleta watu pamoja kupitia maadili ya pamoja, uthamini wa kitamaduni, na uhusiano wa kweli.",
    whatMakesDifferent: "Nini Kinatufanya Tofauti",
    culturalCelebration: "Kusherehekea utamaduni katika kila uhusiano",
    advancedVerification: "Mifumo ya uthibitishaji wa hali ya juu",
    premiumFeatures: "Vipengele vya bora vilivyoundwa kwa uhusiano wenye maana",
    communityFocused: "Jukwaa linalozingatia jamii na uhusiano wa muda halisi",
    contactUs: "Wasiliana Nasi",
    contactDesc: "Una maswali au maoni? Tungependa kusikia kutoka kwako kwa",
    upgradeYourLoveLife: "Boresha Maisha Yako ya Mapenzi",
    premiumDesc: "Fungua vipengele vya bora na pata uhusiano wenye maana na watu wanaoshiriki maadili yako ya kitamaduni",
    mostPopular: "Maarufu Zaidi",
    silver: "Fedha",
    gold: "Dhahabu",
    platinum: "Platinamu",
    perMonth: "/mwezi",
    enhancedDating: "Uzoefu wa mapenzi ulioboreshwa",
    premiumCultural: "Uhusiano wa kitamaduni wa hali ya juu",
    eliteDating: "Uzoefu wa mapenzi wa hali ya juu",
    unlimitedLikes: "Kupenda bila kikomo",
    seeWhoLikedYou: "Ona nani alikupenda",
    superLikesPerDay: "Super Likes kwa siku",
    boostPerMonth: "Boost kwa mwezi",
    noAds: "Hakuna matangazo",
    everythingInSilver: "Kila kitu katika Fedha",
    unlimitedSuperLikes: "Super Likes bila kikomo",
    boostsPerMonth: "Boosts kwa mwezi",
    priorityLikes: "Kupenda kwa kipaumbele",
    readReceipts: "Risiti za kusoma",
    culturalMatchFilter: "Kichujio cha mechi ya kitamaduni",
    everythingInGold: "Kila kitu katika Dhahabu",
    unlimitedBoosts: "Boosts bila kikomo",
    messageBeforeMatching: "Tuma ujumbe kabla ya kuoanishwa",
    prioritySupport: "Msaada wa wateja wa kipaumbele",
    exclusiveEvents: "Ufikiaji wa matukio ya kipekee",
    advancedFilters: "Vichujio vya hali ya juu",
    choose: "Chagua",
    neverRunOut: "Usikose nafasi za kuungana",
    noMoreGuessing: "Hakuna tena kukisia - ona wapenzi wako",
    superBoosts: "Super Boosts",
    getMoreViews: "Pata maoni 10x zaidi ya wasifu",
    culturalFilters: "Vichujio vya Kitamaduni",
    findSharedHeritage: "Pata mechi wanaoshiriki urithi wako",
    faq: "Maswali Yanayoulizwa Mara kwa Mara",
    canCancelAnytime: "Ninaweza kufuta wakati wowote?",
    cancelDesc: "Ndiyo, unaweza kufuta usajili wako wakati wowote. Hakuna maswali.",
    paymentsSecure: "Je, malipo ni salama?",
    paymentsSecureDesc: "Kabisa. Tunatumia usimbaji wa kiwango cha tasnia kulinda maelezo yako ya malipo.",
    profile: "Wasifu",
    editProfile: "Hariri Wasifu",
    settings: "Mipangilio",
    tokens: "Tokeni",
    stats: "Takwimu",
    saveChanges: "Hifadhi Mabadiliko",
    cancel: "Ghairi",
    displayName: "Jina la Kuonyesha",
    bio: "Wasifu Mfupi",
    occupation: "Kazi",
    education: "Elimu",
    interests: "Mapendeleo",
    relationshipGoals: "Malengo ya Uhusiano",
    age: "Umri",
    verificationStatus: "Hali ya Uthibitishaji",
    accountSettings: "Mipangilio ya Akaunti",
    privacySettings: "Mipangilio ya Faragha",
    notificationSettings: "Mipangilio ya Arifa",
    loading: "Inapakia...",
    noMoreProfiles: "Hakuna wasifu zaidi",
    loadMore: "Pakia Zaidi",
    viewProfile: "Ona Wasifu",
    addFriend: "Ongeza Rafiki",
    sendMessage: "Tuma Ujumbe",
    superLike: "Penda Sana",
    like: "Penda",
    pass: "Pita",
    undo: "Tendua",
    boost: "Boost",
    startStreaming: "Anza Kueneza",
    stopStreaming: "Acha Kueneza",
    joinStream: "Jiunge na Mtiririko",
    leaveStream: "Acha Mtiririko",
    viewers: "Watazamaji",
    goLive: "Nenda Moja kwa Moja",
    endStream: "Maliza Mtiririko",
    save: "Hifadhi",
    delete: "Futa",
    edit: "Hariri",
    close: "Funga",
    confirm: "Thibitisha",
    search: "Tafuta",
    filter: "Chuja",
    sort: "Panga",
    next: "Ifuatayo",
    previous: "Iliyotangulia",
    submit: "Wasilisha",
    upload: "Pakia",
    download: "Pakua",
    about: "Kuhusu",
    privacyPolicy: "Sera ya Faragha",
    termsConditions: "Masharti na Hali",
    faqs: "Maswali Yanayoulizwa Mara kwa Mara",
    support: "Msaada",
    newsletterText: "Baki na habari za matukio ya kitamaduni na vidokezo vya kuoanisha. Jisajili kwa jarida letu",
    enterEmail: "Ingiza barua pepe yako",
    subscribe: "Jisajili",
    footerLegalText: "Kwa kubonyeza 'Ingia' / 'Unda akaunti', unakubali",
    termsOfService: "Masharti ya Huduma",
    learnDataProcessing: "Jifunze jinsi tunavyochakata data yako katika",
    cookiesPolicy: "Sera ya Vidakuzi",
    and: "na",
    
    // New comprehensive translations
    termsOfServiceTitle: "Masharti ya Huduma",
    reviewTerms: "Tafadhali soma na kubali masharti yetu",
    agreeTerms: "Ninakubali Masharti ya Huduma na Sera ya Faragha",
    tellAboutYourself: "Tuambie kuhusu wewe",
    basicInformation: "Habari za msingi za wasifu wako",
    username: "Jina la mtumiaji",
    enterUsername: "Ingiza jina lako la mtumiaji",
    usernameDisplay: "Jina la mtumiaji litaonekana kwenye wasifu",
    dateOfBirth: "Tarehe ya Kuzaliwa",
    agePublicNotBirthday: "Umri wako utakuwa wa umma, lakini sio siku yako ya kuzaliwa",
    gender: "Jinsia",
    selectGender: "Chagua jinsia yako",
    man: "Mwanamume",
    woman: "Mwanamke",
    other: "Nyingine",
    sexualOrientation: "Mwelekeo wa Kijinsia",
    selectOrientation: "Chagua mwelekeo wako",
    straight: "Moja kwa moja",
    gay: "Msenge",
    lesbian: "Msagaji",
    bisexual: "Jinsia zote mbili",
    pansexual: "Jinsia zote",
    basicInfo: "Habari za Msingi",
    fewMoreDetails: "Maelezo machache zaidi kukuhusu",
    height: "Urefu",
    selectHeight: "Chagua urefu wako",
    bodyType: "Aina ya Mwili",
    selectBodyType: "Chagua aina ya mwili wako",
    athletic: "Wa michezo",
    slim: "Mwembamba",
    average: "Wa kawaida",
    curvy: "Mviringo",
    heavyset: "Mkubwa",
    relationshipPreferences: "Mapendeleo ya Mahusiano",
    whatLookingFor: "Unatafuta nini?",
    lookingFor: "Natafuta",
    selectLookingFor: "Chagua unachotafuta",
    casualDating: "Mahusiano ya kawaida",
    seriousRelationship: "Mahusiano makubwa",
    friendship: "Urafiki",
    somethingCasual: "Kitu cha kawaida",
    longTermPartner: "Mshirika wa muda mrefu",
    hobbies: "Mambo ya Kufurahisha",
    enterHobbies: "Ingiza mambo yako ya kufurahisha (tenganishwa na mkato)",
    personality: "Aina ya Tabia",
    selectPersonality: "Chagua aina ya tabia yako",
    introvert: "Mwenye kujizuia",
    extrovert: "Mwenye kujitokeza",
    ambivert: "Kati yake",
    addPhotos: "Ongeza Picha",
    uploadYourPhotos: "Pakia picha zako bora (hadi 6)",
    dragDropPhotos: "Buruta na udondoshe picha hapa au bofya ili kutazama",
    dragDropActivePhotos: "Dondosha picha hapa...",
    photos: "Picha",
    letsStart: "Tuanze!",
    continue: "Endelea",
    savingProfile: "Inahifadhi Wasifu...",
    profileVerification: "Uthibitishaji wa Wasifu",
    getOrangeCheckmark: "Pata alama yako ya machungwa",
    alreadyVerified: "Tayari Imethibitishwa!",
    verifiedProfile: "Wasifu Uliothibitishwa",
    profileSuccessfullyVerified: "Wasifu wako umethibitishwa kwa mafanikio na unaonyesha alama ya machungwa.",
    increasedTrust: "Uaminifu Ulioongezeka",
    otherUsersKnowReal: "Watumiaji wengine wanajua wewe ni wa kweli",
    moreMatches: "Mechi Zaidi",
    verifiedProfilesVisibility: "Wasifu zilizothibitishwa zinapata mwonekano zaidi",
    enhancedSecurity: "Usalama Ulioboreshwa",
    protectedFakeProfiles: "Umelindwa dhidi ya wasifu za uongo",
    backToDating: "Rudi kwa Mahusiano",
    getVerifiedTitle: "Pata Uthibitishaji",
    standOut2Step: "Jitofautishe na mchakato wetu salama wa hatua 2 za uthibitishaji",
    howItWorks: "Jinsi inavyofanya kazi:",
    livenessCheck: "Ukaguzi wa Uhai",
    followInstructionsReal: "Fuata maagizo rahisi ili kuthibitisha wewe ni mtu wa kweli",
    faceMatching: "Kulinganisha Uso",
    compareLiveVideo: "Tutalinganisha video yako ya moja kwa moja na picha za wasifu wako",
    orangeCheckmark: "Alama ya Machungwa",
    verifiedBadgeAuthentic: "Pata beji iliyothibitishwa inayoonyesha wewe ni wa kweli",
    requirements: "Mahitaji:",
    cameraAccessVideo: "Ufikiaji wa kamera kwa uthibitishaji wa video",
    goodLighting: "Hali nzuri za mwanga",
    clearProfilePhoto: "Angalau picha moja wazi ya wasifu",
    minutesTime: "Dakika 2-3 za muda wako",
    startVerification: "Anza Uthibitishaji",
    profileRequired: "Wasifu Unahitajika",
    completeProfileVerification: "Tafadhali kamilisha wasifu wako kabla ya uthibitishaji.",
    goToProfile: "Nenda kwa Wasifu",
    privacyPolicyTitle: "Sera ya Faragha",
    termsOfServicePageTitle: "Masharti ya Huduma",
    cookiesPolicyTitle: "Sera ya Vidakuzi",
    lastUpdated: "Imesasishwa mwisho",
    informationWeCollect: "Habari Tunazokusanya",
    howWeUseInfo: "Jinsi Tunavyotumia Habari Yako",
    informationSharing: "Kushiriki Habari",
    dataSecurity: "Usalama wa Data",
    yourPrivacyRights: "Haki Zako za Faragha",
    dataRetention: "Uhifadhi wa Data",
    childrensPrivacy: "Faragha ya Watoto",
    internationalUsers: "Watumiaji wa Kimataifa",
    changesToPolicy: "Mabadiliko ya Sera Hii",
    contactSection: "Wasiliana",
    acceptanceOfTerms: "Kukubali Masharti",
    eligibility: "Ustahiki",
    accountSecurity: "Usalama wa Akaunti",
    userConduct: "Tabia ya Mtumiaji",
    contentGuidelines: "Miongozo ya Maudhui",
    premiumServices: "Huduma za Bora",
    termination: "Kumaliza",
    disclaimers: "Kanusho",
    limitationLiability: "Kikomo cha Dhima",
    governingLaw: "Sheria Inayosimamia",
    contact: "Wasiliana",
    whatAreCookies: "Vidakuzi Ni Nini",
    typesOfCookies: "Aina za Vidakuzi Tunavyotumia",
    thirdPartyCookies: "Vidakuzi vya Wahusika wa Tatu",
    cookieDuration: "Muda wa Vidakuzi",
    managingCookies: "Kusimamia Mapendeleo ya Vidakuzi",
    mobileDevices: "Vifaa vya Mkononi",
    updatesToPolicy: "Masasisho ya Sera Hii",
    pageNotFound: "Ukurasa haujapatikana",
    oopsPageNotFound: "Samahani! Ukurasa haujapatikana",
    returnToHome: "Rudi Nyumbani",
    premiumDating: "Mahusiano ya Bora",
    redefined: "Imefafanuliwa Upya",
    culturalConnections: "Uhusiano wa Kitamaduni",
    experienceAfrocentricLuxury: "Zwa mahusiano ya kifahari ya Kiafrika yenye uhusiano wa kitamaduni wenye nguvu, vipengele vya kipekee vya kueneza, na mahusiano yenye maana yaliyozingatia urithi.",
    startMatching: "Anza Kuoanisha",
    watchDemo: "Tazama Onyesho",
    culturalMembers: "Wanachama wa Kitamaduni",
    matchSuccess: "Mafanikio ya Mechi",
    liveStreamingTitle: "Kueneza Moja kwa Moja",
    premiumDatingExperience: "Uzoefu wa mahusiano ya hali ya juu kwa uhusiano wa kistaarabu",
  },
  yo: {
    tagline: "A fi Àṣà Ṣe Ìsopọ̀",
    createAccount: "Ṣẹda àkáùntì",
    alreadyMember: "Ṣe o ti jẹ́ ọmọ ẹgbẹ́? Wọlé",
    culture: "Àṣà",
    discover: "Ṣàwárí",
    collective: "Àjọpọ̀",
    languages: "Àwọn èdè",
    signIn: "Wọlé",
    joinNow: "Darapọ̀ Nísinsin yìí",
    whyCultureDifferent: "Kí Ni Ìdí Tí \"Àṣà\" Yàtọ̀",
    globalCulture: "Àṣà Àgbáyé",
    globalCultureDesc: "Èyí jẹ́ àyè tí àṣà ṣe àtìlẹyìn. Yálà àṣà ọ̀rẹ́, àṣà ìfẹ́, tàbí àṣà ìbáṣepọ̀. Sopọ̀ mọ́ àwọn ènìyàn láti gbogbo igun ayé.",
    virtualDates: "Àwọn Àpàdé Aládàáṣe",
    virtualDatesDesc: "Ṣàwárí àwọn ọ̀nà tuntun láti sopọ̀, bíi sísè oúnjẹ papọ̀ nipasẹ ìpè fídíò, pínpín ewì àyànfẹ́ rẹ.",
    sharedEvents: "Àwọn Ìṣẹ̀lẹ̀ Àjọ",
    sharedEventsDesc: "Lọ sí àwọn ìṣẹ̀lẹ̀ àṣà pàtàkì lórí ayélujára àti lẹ́yìn ayélujára: àjọ fíìmù, àjọ orin, ìdíje ewì.",
    curatedPlaylists: "Àtòjọ Orin Tí A Yàn",
    curatedPlaylistsDesc: "Lọ́sẹ̀ kọ̀ọ̀kan, gbádùn àtòjọ orin tí a yàn fún àwọn ẹ̀yà àṣà oríṣiríṣi.",
    intellectualDialogue: "Ìjíròrò Ọgbọ́n àti Ìṣẹ̀dá",
    intellectualDialogueDesc: "Kópa nínú àwọn ìjíròrò tó ní ìtumọ̀, yálà nípa ìmọ̀-ọgbọ́n, lítíréṣọ̀, tàbí fíìmù.",
    discoverMeaningful: "Ṣàwárí Àwọn Ìsopọ̀ Tó Ní Ìtumọ̀",
    culturalQuiz: "Ìdánwò Ìbáṣepọ̀ Àṣà",
    culturalQuizDesc: "Ṣàwárí irú ìrírí àṣà wo ní ó wù ọkàn rẹ nipasẹ ìdánwò tí ó rọrùn ṣùgbọ́n tó ní ìmúra.",
    personalizedMatch: "Ìṣòfohun Tìrẹ",
    personalizedMatchDesc: "Nípa lílo àwọn àyàn àṣà rẹ, ìfẹ́, àti àwọn àbùdá ẹni, a ṣòfohun ọ pẹ̀lú àwọn mìíràn tí ó ní ìgbésí ayé kanna.",
    shareConnect: "Pín àti Sopọ̀",
    shareConnectDesc: "Kópa nínú àwọn ìjíròrò tó fanimọ́ra, pààrọ̀ àwọn iṣẹ́ ìṣẹ̀dá, ṣàwárí àwọn ìṣẹ̀lẹ̀ àṣà àkànṣe.",
    memberStories: "Àwọn Ìtàn Àwọn Ọmọ Ẹgbẹ́ Wa",
    getInspired: "Gba Ìmísí, Ṣàwárí Papọ̀",
    readyExperience: "Ṣe o Ṣetán Láti Ní Ìsopọ̀ Tó Yàtọ̀?",
    embraceCulture: "Gba àṣà, iṣẹ́-ọnà, àti ọkàn—wa ẹni tó yẹ kí ó mọ̀ ọ́ gidi.",
    createProfileNow: "Ṣẹda Profaili Rẹ Nísinsin yìí",
    back: "Padà",
    welcomeBack: "Káàbọ̀ padà",
    email: "Ímeèlì",
    password: "Ọ̀rọ̀ ìpamọ́",
    location: "Ìbùdó",
    confirmPassword: "Jẹ́rìísí Ọ̀rọ̀ ìpamọ́",
    passwordMinimum: "Ọ̀rọ̀ ìpamọ́ (ó kéré jù lẹ́tà 10)",
    createStrongPassword: "Ṣẹda ọ̀rọ̀ ìpamọ́ tó lágbára",
    confirmYourPassword: "Jẹ́rìísí ọ̀rọ̀ ìpamọ́ rẹ",
    yourPassword: "Ọ̀rọ̀ ìpamọ́ rẹ",
    signingIn: "Ń Wọlé...",
    creatingAccount: "Ń Ṣẹda Àkáùntì...",
    dontHaveAccount: "Ko ní àkáùntì?",
    meaningfulConnections: "Ní ìrírí àwọn ìsopọ̀ tó ní ìtumọ̀ tó dá lórí àṣà àti ogún",
    continueJourney: "Tẹ̀síwájú ìrìnàjò rẹ ti àwọn ìsopọ̀ tó ní ìtumọ̀",
    messages: "Àwọn ìfiráńṣẹ́",
    liveStream: "Ìṣàn Láàyè",
    getVerified: "Jẹ́ Kí A Jẹ́rìí Rẹ",
    premium: "Alágà",
    welcome: "Káàbọ̀",
    signOut: "Jáde",
    friends: "Àwọn ọ̀rẹ́",
    matches: "Àwọn Ìbáṣepọ̀",
    aboutOloo: "Nípa Òloo",
    culturedConnection: "A fi Àṣà Ṣe Ìsopọ̀",
    aboutDesc: "Òloo jẹ́ pẹpẹ ìfẹ́ alágà tí a ṣe àpẹẹrẹ láti ṣe ayẹyẹ àṣà Áfríkà.",
    ourMission: "Iṣẹ́ Àpinfunni Wa",
    missionDesc: "A gbà pé a ń mú àwọn ènìyàn papọ̀ nipasẹ àwọn ìyè tí a ṣàjọ, ìmọ̀yì àṣà, àti àwọn ìsopọ̀ gidi.",
    whatMakesDifferent: "Kí Ni Ó Jẹ́ Kí A Yàtọ̀",
    culturalCelebration: "Ayẹyẹ àṣà ní àárín gbogbo ìsopọ̀",
    advancedVerification: "Àwọn ètò ìjẹ́rìísí tó ga",
    premiumFeatures: "Àwọn ẹ̀yà alágà tí a ṣe fún àwọn ìbáṣepọ̀ tó ní ìtumọ̀",
    communityFocused: "Pẹpẹ tó dojúkọ àwùjọ pẹ̀lú àwọn ìsopọ̀ àsìkò-gidi",
    contactUs: "Kàn Sí Wa",
    contactDesc: "Ṣe o ní àwọn ìbéèrè tàbí èrò? A fẹ́ láti gbọ́ látọ̀dọ̀ rẹ ní",
    upgradeYourLoveLife: "Ṣe Ìmúdára Ìgbésí Ayé Ìfẹ́ Rẹ",
    premiumDesc: "Ṣí àwọn ẹ̀yà alágà àti rí àwọn ìsopọ̀ tó ní ìtumọ̀ pẹ̀lú àwọn ènìyàn tó ní àwọn ìyè àṣà kanna",
    mostPopular: "Olókìkí Jùlọ",
    silver: "Fàdákà",
    gold: "Wúrà",
    platinum: "Platinum",
    perMonth: "/oṣù",
    enhancedDating: "Ìrírí ìfẹ́ tó pọ̀ sí i",
    premiumCultural: "Àwọn ìsopọ̀ àṣà alágà",
    eliteDating: "Ìrírí ìfẹ́ àṣàyàn",
    unlimitedLikes: "Àwọn ìfẹ́ràn láìní òpin",
    seeWhoLikedYou: "Wo ẹni tó fẹ́ràn ọ",
    superLikesPerDay: "Super Likes lójoojúmọ́",
    boostPerMonth: "Boost ní oṣù",
    noAds: "Kò sí àwọn ìpolongo",
    everythingInSilver: "Gbogbo nǹkan ní Fàdákà",
    unlimitedSuperLikes: "Super Likes láìní òpin",
    boostsPerMonth: "Boosts ní oṣù",
    priorityLikes: "Àwọn ìfẹ́ràn pàtàkì",
    readReceipts: "Àwọn ìrísí kíkà",
    culturalMatchFilter: "Àṣẹ ìbáṣepọ̀ àṣà",
    everythingInGold: "Gbogbo nǹkan ní Wúrà",
    unlimitedBoosts: "Boosts láìní òpin",
    messageBeforeMatching: "Firánṣẹ́ ṣáájú ìbáṣepọ̀",
    prioritySupport: "Àtìlẹyìn oníbàárà pàtàkì",
    exclusiveEvents: "Ìwọlé sí àwọn ìṣẹ̀lẹ̀ àkànṣe",
    advancedFilters: "Àwọn àṣẹ tó ga",
    choose: "Yan",
    neverRunOut: "Má ṣe kùnà ní àwọn àǹfààní láti sopọ̀",
    noMoreGuessing: "Kò sí ìṣirò mọ́ - wo àwọn oníbùkún rẹ",
    superBoosts: "Super Boosts",
    getMoreViews: "Gba àwọn ìwò profaili 10x sí i",
    culturalFilters: "Àwọn Àṣẹ Àṣà",
    findSharedHeritage: "Wa àwọn ìbáṣepọ̀ tó ní ogún kanna",
    faq: "Àwọn Ìbéèrè Tí A Máa Ń Béèrè",
    canCancelAnytime: "Ṣe mo lè fagilee nígbàkúgbà?",
    cancelDesc: "Bẹẹni, o lè fagilee ìforúkọsílẹ̀ rẹ nígbàkúgbà. Kò sí ìbéèrè.",
    paymentsSecure: "Ṣe àwọn ìsanwó wà láìléwu?",
    paymentsSecureDesc: "Dájúdájú. A lo ìsímí tí ó tọ́ ilé-iṣẹ́ láti dáàbò bo àlàyé ìsanwó rẹ.",
    profile: "Profaili",
    editProfile: "Ṣàtúnṣe Profaili",
    settings: "Àwọn Ààtò",
    tokens: "Àwọn Àmì",
    stats: "Àwọn Àkọsílẹ̀",
    saveChanges: "Fi Àwọn Àyípadà Pamọ́",
    cancel: "Fagilee",
    displayName: "Orúkọ Àfihàn",
    bio: "Ìtàn Kúkúrú",
    occupation: "Iṣẹ́",
    education: "Ẹ̀kọ́",
    interests: "Àwọn Ìfẹ́",
    relationshipGoals: "Àwọn Ibi-Afẹ́dé Ìbáṣepọ̀",
    age: "Ọjọ́ Orí",
    verificationStatus: "Ipò Ìjẹ́rìísí",
    accountSettings: "Àwọn Ààtò Àkáùntì",
    privacySettings: "Àwọn Ààtò Ìkọ̀kọ̀",
    notificationSettings: "Àwọn Ààtò Ìkíláṣẹ́",
    loading: "Ń ṣe ìgbéjáde...",
    noMoreProfiles: "Kò sí àwọn profaili mọ́",
    loadMore: "Gbe Díẹ̀ Síi",
    viewProfile: "Wo Profaili",
    addFriend: "Fi Ọ̀rẹ́ Kún",
    sendMessage: "Fi Ìfiráńṣẹ́ Ránṣẹ́",
    superLike: "Fẹ́ràn Púpọ̀",
    like: "Fẹ́ràn",
    pass: "Kọjá",
    undo: "Ìdápadà",
    boost: "Boost",
    startStreaming: "Bẹ̀rẹ̀ Ìṣàn",
    stopStreaming: "Dá Ìṣàn Dúró",
    joinStream: "Darapọ̀ mọ́ Ìṣàn",
    leaveStream: "Fi Ìṣàn Sílẹ̀",
    viewers: "Àwọn Olutọ́jú",
    goLive: "Lọ Láàyè",
    endStream: "Parí Ìṣàn",
    save: "Fi Pamọ́",
    delete: "Pajẹ",
    edit: "Ṣàtúnṣe",
    close: "Tì",
    confirm: "Jẹ́rìísí",
    search: "Wá",
    filter: "Àṣẹ",
    sort: "Ṣètò",
    next: "Tókàn",
    previous: "Tẹ́lẹ̀",
    submit: "Fàṣípò",
    upload: "Gbe Sókè",
    download: "Gbe Sílẹ̀",
    about: "Nípa",
    privacyPolicy: "Ìlànà Ìkọ̀kọ̀",
    termsConditions: "Àwọn Òfin àti Ipò",
    faqs: "Àwọn Ìbéèrè Tí A Máa Ń Béèrè",
    support: "Àtìlẹyìn",
    newsletterText: "Wà ní ìmúdójúìwọ̀n pẹ̀lú àwọn ìṣẹ̀lẹ̀ àṣà àkànṣe àti àwọn ìmọ̀ràn ìṣòfohun. Forúkọsílẹ̀ fún ìròyìn wa",
    enterEmail: "Tẹ ímeèlì rẹ sínú",
    subscribe: "Forúkọsílẹ̀",
    footerLegalText: "Nípa tite 'Wọlé' / 'Ṣẹda àkáùntì', o fara mọ́ wa",
    termsOfService: "Àwọn Òfin Iṣẹ́",
    learnDataProcessing: "Kọ́ bí a ṣe ń ṣiṣẹ́ lórí data rẹ nínú wa",
    cookiesPolicy: "Ìlànà Cookies",
    and: "àti",
  },
  zu: {
    tagline: "Sihlanganiswa Ngamasiko",
    createAccount: "Dala i-akhawunti",
    alreadyMember: "Usuyilungu? Ngena ngemvume",
    culture: "Amasiko",
    discover: "Thola",
    collective: "Sibumbene",
    languages: "Izilimi",
    signIn: "Ngena",
    joinNow: "Joyina Manje",
    whyCultureDifferent: "Kungani \"Amasiko\" Ehlukile",
    globalCulture: "Amasiko Omhlaba",
    globalCultureDesc: "Lena indawo eyakhiwe ngamasiko. Kungaba amasiko obungani, amasiko othando, noma ngaphezulu. Xhumana nabantu abavela ezingosini zonke zomhlaba.",
    virtualDates: "Izingcebeleko Ze-inthanethi",
    virtualDatesDesc: "Thola izindlela ezintsha zokuxhumana, njengokupheka ndawonye ngevidiyo, ukwabelana ngenkondlo yakho oyithandayo.",
    sharedEvents: "Imicimbi Eyabiwe",
    sharedEventsDesc: "Vakashela imicimbi yamasiko eyodwa ku-inthanethi nangaphandle kwe-inthanethi: imibukiso yefilimu, imicimbi yomculo, izinkundla zenkondlo.",
    curatedPlaylists: "Uhlu Lokukhethiwe",
    curatedPlaylistsDesc: "Masonto onke, jabulela uhlu lomculo lokukhethwe olwenziwe ngezinhlobo zamasiko ahlukene.",
    intellectualDialogue: "Izingxoxo Zobulungiswa Nokudalwa",
    intellectualDialogueDesc: "Hlanganyela ezingxoxweni ezinomqondo, nokho kungaba ngokuhlakanipha, izincwadi, noma ifilimu.",
    discoverMeaningful: "Thola Ukuxhumana Okunomqondo",
    culturalQuiz: "Ukuvivinya Ukuhambisana Kwamasiko",
    culturalQuizDesc: "Thola ukuthi yiziphi izimo zamasiko ezivumelana nomphefumulo wakho ngokuvivinya okulula kodwa olucabangayo.",
    personalizedMatch: "Ukufanelana Komuntu Siqu",
    personalizedMatchDesc: "Sisebenzisa intshisekelo yakho yamasiko, izifiso, nezimpawu zomuntu, sikufanise nabanye ababelana ngokuphila okufanayo.",
    shareConnect: "Yabelana Futhi Uxhumane",
    shareConnectDesc: "Hlanganyela ezingxoxweni ezibandakanyayo, shintshana ngemisebenzi yobuciko, thola imicimbi yamasiko eyodwa.",
    memberStories: "Izindaba Zamalungu Ethu",
    getInspired: "Thola Ugqozi, Hlolisisa Ndawonye",
    readyExperience: "Ukulungele Ukuzwa Ukuxhumana Okwehlukile?",
    embraceCulture: "Yamukela amasiko, ubuciko, nomphefumulo—thola umuntu okwazi ngempela.",
    createProfileNow: "Dala Iphrofayela Yakho Manje",
    back: "Buyela emuva",
    welcomeBack: "Siyakwamukela futhi",
    email: "I-imeyili",
    password: "Iphasiwedi",
    location: "Indawo",
    confirmPassword: "Qinisekisa Iphasiwedi",
    passwordMinimum: "Iphasiwedi (okungenani izinhlamvu ezi-10)",
    createStrongPassword: "Dala iphasiwedi eqinile",
    confirmYourPassword: "Qinisekisa iphasiwedi yakho",
    yourPassword: "Iphasiwedi yakho",
    signingIn: "Iyangenisa...",
    creatingAccount: "Idala I-akhawunti...",
    dontHaveAccount: "Awunayo i-akhawunti?",
    meaningfulConnections: "Zwa ukuxhumana okunomqondo okuzinze emasikweni nasefa",
    continueJourney: "Qhubeka nohambo lwakho lokuxhumana okunomqondo",
    messages: "Imilayezo",
    liveStream: "Ukusakaza Bukhoma",
    getVerified: "Thola Ukuqinisekiswa",
    premium: "I-Premium",
    welcome: "Siyakwamukela",
    signOut: "Phuma",
    friends: "Abangane",
    matches: "Ukufanelana",
    aboutOloo: "Mayelana Ne-Òloo",
    culturedConnection: "Sihlanganiswa Ngamasiko",
    aboutDesc: "I-Òloo iyinkundla yothando ephezulu eyenzelwe ukugubha amasiko ase-Afrika kuyilapho ikhuthaza ukuxhumana okunomqondo kulo lonke izwe.",
    ourMission: "Umsebenzi Wethu",
    missionDesc: "Sikholelwa ekuhlanganiseni abantu ngamanani ahlanganisiwe, ukwazisa amasiko, nokuxhumana kwangempela.",
    whatMakesDifferent: "Yini Esenza Sehluke",
    culturalCelebration: "Ukugubha amasiko enhliziyweni yonke ukuxhumana",
    advancedVerification: "Izinhlelo zokuqinisekisa eziphakeme",
    premiumFeatures: "Izici ze-premium ezenzelwe ubudlelwano obunomqondo",
    communityFocused: "Inkundla egxile emphakathini enokuxhumana kwesikhathi sangempela",
    contactUs: "Xhumana Nathi",
    contactDesc: "Unemibuzo noma impendulo? Singathanda ukuzwa kuwe ku",
    upgradeYourLoveLife: "Thuthukisa Ukuphila Kwakho Kothando",
    premiumDesc: "Vula izici ze-premium futhi uthole ukuxhumana okunomqondo nabantu ababelana ngamanani akho amasiko",
    mostPopular: "Okuthandwa Kakhulu",
    silver: "Isiliva",
    gold: "Igolide",
    platinum: "I-Platinum",
    perMonth: "/ngenyanga",
    enhancedDating: "Isipiliyoni sothando esithuthukisiwe",
    premiumCultural: "Ukuxhumana kwamasiko okusezingeni eliphezulu",
    eliteDating: "Isipiliyoni sothando esisezingeni eliphezulu",
    unlimitedLikes: "Ukuthanda okungenamkhawulo",
    seeWhoLikedYou: "Bona ukuthi ubani okuthandile",
    superLikesPerDay: "Ama-Super Likes ngosuku",
    boostPerMonth: "I-Boost ngenyanga",
    noAds: "Ayikho izikhangiso",
    everythingInSilver: "Konke Ku-Silver",
    unlimitedSuperLikes: "Ama-Super Likes angenamkhawulo",
    boostsPerMonth: "Ama-Boosts ngenyanga",
    priorityLikes: "Ukuthanda okubalulekile",
    readReceipts: "Amarisidi okufunda",
    culturalMatchFilter: "Isihlungi sokufanelana kwamasiko",
    everythingInGold: "Konke Ku-Gold",
    unlimitedBoosts: "Ama-Boosts angenamkhawulo",
    messageBeforeMatching: "Thumela umlayezo ngaphambi kokufanelana",
    prioritySupport: "Ukusekela kwamakhasimende okubalulekile",
    exclusiveEvents: "Ukufinyelela kwimicimbi eyodwa",
    advancedFilters: "Izihlungi eziphezulu",
    choose: "Khetha",
    neverRunOut: "Ungapheli amathuba okuxhumana",
    noMoreGuessing: "Akusekho ukulinganisa - bona abakuthandayo",
    superBoosts: "Ama-Super Boosts",
    getMoreViews: "Thola ukubukwa kwephrofayela okungu-10x okuningi",
    culturalFilters: "Izihlungi Zamasiko",
    findSharedHeritage: "Thola ukufanelana okwabelana ngefa",
    faq: "Imibuzo Ebuzwa Njalo",
    canCancelAnytime: "Ngingakhansela nini na?",
    cancelDesc: "Yebo, ungakhansela ukubhalisa kwakho nganoma yisiphi isikhathi. Ayikho imibuzo.",
    paymentsSecure: "Ingabe inkokhelo iphephile?",
    paymentsSecureDesc: "Impela. Sisebenzisa ukubethela izinga lombuso ukuvikela ulwazi lwakho lokukhokha.",
    profile: "Iphrofayela",
    editProfile: "Hlela Iphrofayela",
    settings: "Izilungiselelo",
    tokens: "Amathokheni",
    stats: "Izibalo",
    saveChanges: "Londoloza Izinguquko",
    cancel: "Khansela",
    displayName: "Igama Lokubonakalisa",
    bio: "Ibhayografi",
    occupation: "Umsebenzi",
    education: "Imfundo",
    interests: "Izintshisekelo",
    relationshipGoals: "Izinhloso Zobudlelwano",
    age: "Ubudala",
    verificationStatus: "Isimo Sokuqinisekisa",
    accountSettings: "Izilungiselelo Ze-akhawunti",
    privacySettings: "Izilungiselelo Zobumfihlo",
    notificationSettings: "Izilungiselelo Zezaziso",
    loading: "Iyalayisha...",
    noMoreProfiles: "Azisekho iziphrofayela",
    loadMore: "Layisha Okuningi",
    viewProfile: "Buka Iphrofayela",
    addFriend: "Engeza Umngane",
    sendMessage: "Thumela Umlayezo",
    superLike: "I-Super Like",
    like: "Uyathanda",
    pass: "Dlulula",
    undo: "Hlehlisa",
    boost: "I-Boost",
    startStreaming: "Qala Ukusakaza",
    stopStreaming: "Misa Ukusakaza",
    joinStream: "Joyina Ukusakaza",
    leaveStream: "Shiya Ukusakaza",
    viewers: "Ababukeli",
    goLive: "Hamba Bukhoma",
    endStream: "Qeda Ukusakaza",
    save: "Londoloza",
    delete: "Susa",
    edit: "Hlela",
    close: "Vala",
    confirm: "Qinisekisa",
    search: "Sesha",
    filter: "Hlunga",
    sort: "Hlenga",
    next: "Okulandelayo",
    previous: "Okwedlule",
    submit: "Thumela",
    upload: "Layisha",
    download: "Landa",
    about: "Mayelana",
    privacyPolicy: "Inqubomgomo Yobumfihlo",
    termsConditions: "Imigomo Nemibandela",
    faqs: "Imibuzo Ebuzwa Njalo",
    support: "Ukusekela",
    newsletterText: "Hlala unolwazi ngemicimbi yamasiko eyodwa namathiphu okufanelana. Bhalisela incwadi yezindaba yethu",
    enterEmail: "Faka i-imeyili yakho",
    subscribe: "Bhalisa",
    footerLegalText: "Ngokuthepha 'Ngena' / 'Dala i-akhawunti', uyavuma",
    termsOfService: "Imigomo Yesevisi",
    learnDataProcessing: "Funda indlela esicubungula ngayo idatha yakho ku",
    cookiesPolicy: "Inqubomgomo Yamakhukhi",
    and: "kanye",
  },
  am: {
    tagline: "በባህል የተገናኘን",
    createAccount: "መለያ ፍጠር",
    alreadyMember: "ቀድሞውኑ አባል ነዎት? ግባ",
    culture: "ባህል",
    discover: "አግኝ",
    collective: "አንድነት",
    languages: "ቋንቋዎች",
    signIn: "ግባ",
    joinNow: "አሁን ተቀላቀል",
    back: "ተመለስ",
    welcomeBack: "እንኳን ደህና መጡ",
    email: "ኢሜይል",
    password: "የይለፍ ቃል",
    location: "አድራሻ",
    messages: "መልዕክቶች",
    friends: "ጓደኞች",
    profile: "መገለጫ",
    loading: "በመጫን ላይ...",
    like: "ይወዱ",
  },
  ha: {
    tagline: "An Haɗa Mu Ta Al'ada",
    createAccount: "Ƙirƙiri asusun",
    alreadyMember: "Kai memba ne? Shiga",
    culture: "Al'ada",
    discover: "Gano",
    collective: "Tare",
    languages: "Harsuna",
    signIn: "Shiga",
    joinNow: "Shiga Yanzu",
    back: "Koma",
    welcomeBack: "Maraba da dawowa",
    email: "Imel",
    password: "Kalmar sirri",
    location: "Wuri",
    messages: "Saƙonni",
    friends: "Abokai",
    profile: "Bayanan",
    loading: "Ana lodawa...",
    like: "So",
  },
  ig: {
    tagline: "Ejikọtara N'omenala",
    createAccount: "Mepụta akaụntụ",
    alreadyMember: "Ị bụlarị onye òtù? Banye",
    culture: "Omenala",
    discover: "Chọpụta",
    collective: "Ọnụ",
    languages: "Asụsụ",
    signIn: "Banye",
    joinNow: "Sonye Ugbu a",
    back: "Laghachi azụ",
    welcomeBack: "Nnọọ ọzọ",
    email: "Email",
    password: "Okwuntụghe",
    location: "Ebe",
    messages: "Ozi",
    friends: "Ndị enyi",
    profile: "Profaịlụ",
    loading: "Na-ebugo...",
    like: "Masị",
  },
  // Adding other languages with comprehensive basic translations
  so: { 
    tagline: "Dhaqan ku Xidhan", 
    createAccount: "Samee koonto", 
    culture: "Dhaqan", 
    languages: "Luqadaha",
    signIn: "Gal",
    joinNow: "Ku biir hadda",
    back: "Dib u noqo",
    email: "Iimaylka",
    password: "Furaha sirta ah",
    messages: "Farriimaha",
    friends: "Saaxiibada",
    profile: "Astaanta",
    loading: "Waa la soo rarayo...",
    like: "Jeclaansho",
    discover: "Arag",
    welcome: "Soo dhawow",
  },
  om: { 
    tagline: "Aadaa Waliin Walitti Dhufeenya", 
    createAccount: "Akkaawuntii Uumi", 
    culture: "Aadaa", 
    languages: "Afaanota",
    signIn: "Seeni",
    joinNow: "Amma makuu",
    back: "Duubatti deebi'i",
    email: "Iimeelii",
    password: "Jecha icciitii",
    messages: "Ergaawwan",
    friends: "Hiriyyoota",
    profile: "Piroofaayilii",
    loading: "Fe'amaa jira...",
    like: "Jaalata",
    discover: "Qorata",
    welcome: "Baga nagaan dhuftan",
  },
  sn: { 
    tagline: "Takabatana Netsika", 
    createAccount: "Gadzira account", 
    culture: "Tsika", 
    languages: "Mitauro",
    signIn: "Pinda",
    joinNow: "Bata izvozvi",
    back: "Dzoka kumashure",
    email: "Imeyiri",
    password: "Password",
    messages: "Mameseji",
    friends: "Shamwari",
    profile: "Profayiri",
    loading: "Kuri kurodha...",
    like: "Chida",
    discover: "Tsvaga",
    welcome: "Mauya",
  },
  wo: { 
    tagline: "Yoon Na Ci Aadaa", 
    createAccount: "Sos konte", 
    culture: "Aadaa", 
    languages: "Làkk",
    signIn: "Dugg",
    joinNow: "Bokk leegi",
    back: "Dellu",
    email: "Iméel",
    password: "Bàttub gannaaw",
    messages: "Bataaxal",
    friends: "Xarit",
    profile: "Profil",
    loading: "Dafay yeb...",
    like: "Bëgg",
    discover: "Gis",
    welcome: "Dalal ak jàmm",
  },
  xh: { 
    tagline: "Sidibene Ngenkcubeko", 
    createAccount: "Yenza i-akhawunti", 
    culture: "Inkcubeko", 
    languages: "Iilwimi",
    signIn: "Ngena",
    joinNow: "Joyina ngoku",
    back: "Buyela umva",
    email: "I-imeyile",
    password: "Igama lokugqitha",
    messages: "Imiyalezo",
    friends: "Abahlobo",
    profile: "Iprofayile",
    loading: "Iyalayisha...",
    like: "Uyathanda",
    discover: "Fumanisa",
    welcome: "Wamkelekile",
  },
  ti: { 
    tagline: "ብባህሊ ተራኺብና", 
    createAccount: "ኣካውንት ፍጠር", 
    culture: "ባህሊ", 
    languages: "ቋንቋታት",
    signIn: "ኣቱ",
    joinNow: "ሕጂ ተጸምበር",
    back: "ተመለስ",
    email: "ኢመይል",
    password: "ፓስዎርድ",
    messages: "መልእኽትታት",
    friends: "ኣዕሩኽ",
    profile: "መገለጺ",
    loading: "ይጽዕን ኣሎ...",
    like: "ይፈቱ",
    discover: "ርኸብ",
    welcome: "እንቋዕ ብደሐን መጻእኩም",
  },
  af: { 
    tagline: "Kultuurlik Verbind", 
    createAccount: "Skep rekening", 
    culture: "Kultuur", 
    languages: "Tale",
    signIn: "Teken in",
    joinNow: "Sluit nou aan",
    back: "Terug",
    email: "E-pos",
    password: "Wagwoord",
    messages: "Boodskappe",
    friends: "Vriende",
    profile: "Profiel",
    loading: "Laai...",
    like: "Hou van",
    discover: "Ontdek",
    welcome: "Welkom",
  },
  ak: { 
    tagline: "Amanneɛ Mu Nkitahodie", 
    createAccount: "Yɛ akontaabu", 
    culture: "Amanneɛ", 
    languages: "Kasa",
    signIn: "Hyɛ mu",
    joinNow: "Ka ho seesei",
    back: "San kɔ",
    email: "Ímeélo",
    password: "Password",
    messages: "Nkrasɛm",
    friends: "Nnamfo",
    profile: "Profaele",
    loading: "Ɛrekyerɛ...",
    like: "Dɔ",
    discover: "Hwehwɛ",
    welcome: "Akwaaba",
  },
  rw: { 
    tagline: "Duhujwe n'Umuco", 
    createAccount: "Kora konti", 
    culture: "Umuco", 
    languages: "Indimi",
    signIn: "Injira",
    joinNow: "Injira ubu",
    back: "Subira inyuma",
    email: "Imeyili",
    password: "Ijambo banga",
    messages: "Ubutumwa",
    friends: "Inshuti",
    profile: "Umwirondoro",
    loading: "Birapakira...",
    like: "Gukunda",
    discover: "Shakisha",
    welcome: "Murakaza neza",
  },
  ln: { 
    tagline: "Tokutani na Mimeseno", 
    createAccount: "Kela kɔnti", 
    culture: "Mimeseno", 
    languages: "Nkótá",
    signIn: "Kɔta",
    joinNow: "Kɔta sikawa",
    back: "Zɔnga nsima",
    email: "Imɛlɛ",
    password: "Liloba ya nkuku",
    messages: "Bansango",
    friends: "Baninga",
    profile: "Profil",
    loading: "Ezali kokɔta...",
    like: "Kolinga",
    discover: "Luka",
    welcome: "Boyei malamu",
  },
  ff: { 
    tagline: "Jokkondiranɗe e Golle", 
    createAccount: "Sos konte", 
    culture: "Golle", 
    languages: "Ɗemɗe",
    signIn: "Naatnu",
    joinNow: "Naatnu jooni",
    back: "Rutto",
    email: "Iimeel",
    password: "Finnde koyre",
    messages: "Batakuuji",
    friends: "Gonga'en",
    profile: "Profil",
    loading: "Ena loowa...",
    like: "Yiɗi",
    discover: "Yiylowol",
    welcome: "On jaabani",
  },
  bem: { 
    tagline: "Twabungana mu Micila", 
    createAccount: "Panga akawunti", 
    culture: "Micila", 
    languages: "Imilaka",
    signIn: "Ingila",
    joinNow: "Ingila nomba",
    back: "Bwelela kunuma",
    email: "Imeili",
    password: "Amasansa",
    messages: "Amilandu",
    friends: "Abwanike",
    profile: "Profayili",
    loading: "Yalaposa...",
    like: "Taisa",
    discover: "Ipusha",
    welcome: "Mwaisheni",
  },
  tn: { 
    tagline: "Re Kopane ka Setso", 
    createAccount: "Tlhama akhaonto", 
    culture: "Setso", 
    languages: "Maleme",
    signIn: "Tsena",
    joinNow: "Tsena gone jaanong",
    back: "Boela morago",
    email: "Imeili",
    password: "Lentswe la sephiri",
    messages: "Melaetsa",
    friends: "Ditsala",
    profile: "Porofaele",
    loading: "E a lesa...",
    like: "Rata",
    discover: "Batla",
    welcome: "Kamogelo",
  },
  tw: { 
    tagline: "Amammerɛ Mu Nkabom", 
    createAccount: "Yɛ akontaabu", 
    culture: "Amammerɛ", 
    languages: "Kasa",
    signIn: "Kɔ mu",
    joinNow: "Kɔ mu seesei",
    back: "San ba",
    email: "Imeili",
    password: "Ahyɛnsodeɛ",
    messages: "Nkrasɛm",
    friends: "Nnamfonom",
    profile: "Krataa",
    loading: "Ɛrekyerɛ...",
    like: "Dɔ",
    discover: "Hwehwɛ",
    welcome: "Yɛma wo akwaaba",
  },
};
