import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 
  | 'en' | 'sw' | 'yo' | 'zu' | 'am' | 'ha' | 'ig' | 'so' | 'om' 
  | 'sn' | 'wo' | 'xh' | 'ti' | 'af' | 'ak' | 'rw' | 'ln' | 'ff' 
  | 'bem' | 'tn' | 'tw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Landing page
    tagline: "Cultured in Connection",
    createAccount: "Create account",
    alreadyMember: "Already a member? Log in",
    culture: "Culture",
    discover: "Discover",
    collective: "Collective",
    languages: "Languages",
    signIn: "Sign In",
    joinNow: "Join Now",
    whyCultureDifferent: "Why \"The Culture\" Is Different",
    globalCulture: "Global Culture",
    globalCultureDesc: "This is a culture inspired space. Be it friendship culture, dating culture, relationship culture and even beyond. Connect with people from all corners of the globe—find your tribe.",
    virtualDates: "Virtual Dates",
    virtualDatesDesc: "Explore new ways to connect, like cooking a dish together over video call, sharing your favorite poetry, or showing each other local art galleries.",
    sharedEvents: "Shared Events",
    sharedEventsDesc: "Attend exclusive online and offline cultural events: film festivals, music festivals, poetry slams, or even regional festivals. Meet your match while immersing yourself in art, culture, and history.",
    curatedPlaylists: "Curated Playlists",
    curatedPlaylistsDesc: "Each week, enjoy curated playlists designed around different cultural genres. Find someone to vibe with over an Afrobeat playlist or discover classical Eastern music together.",
    intellectualDialogue: "Intellectual & Creative Dialogue",
    intellectualDialogueDesc: "Engage in meaningful conversations, whether it's about philosophy, literature, or film. Our platform's focus is on building deeper emotional and intellectual connections.",
    discoverMeaningful: "Discover Meaningful Connections",
    culturalQuiz: "Cultural Compatibility Quiz",
    culturalQuizDesc: "Find out which cultural experiences resonate with your soul through a simple yet thoughtful quiz that reflects your values, interests, and artistic tastes.",
    personalizedMatch: "Personalized Matchmaking",
    personalizedMatchDesc: "Using your cultural preferences, passions, and personality traits, we match you with others who share similar lifestyles, traditions, and ideology.",
    shareConnect: "Share and Connect",
    shareConnectDesc: "Participate in engaging conversations, exchange creative works, explore unique cultural events, or enjoy a virtual dinner date with someone who speaks your cultural language.",
    memberStories: "Our Members' Stories",
    getInspired: "Get Inspired, Explore Together",
    readyExperience: "Ready to Experience a Connection Like No Other?",
    embraceCulture: "Embrace culture, art, and soul—find someone who truly gets you.",
    createProfileNow: "Create Your Profile Now",
    
    // Auth & Sign In
    back: "Back",
    welcomeBack: "Welcome back",
    email: "Email",
    password: "Password",
    location: "Location",
    confirmPassword: "Confirm Password",
    passwordMinimum: "Password (minimum 10 characters)",
    createStrongPassword: "Create a strong password",
    confirmYourPassword: "Confirm your password",
    yourPassword: "Your password",
    signingIn: "Signing In...",
    creatingAccount: "Creating Account...",
    dontHaveAccount: "Don't have an account?",
    meaningfulConnections: "Experience meaningful connections rooted in culture and heritage",
    continueJourney: "Continue your journey of meaningful connections",
    
    // Navigation
    messages: "Messages",
    liveStream: "Live Stream",
    getVerified: "Get Verified",
    premium: "Premium",
    welcome: "Welcome",
    signOut: "Sign Out",
    friends: "Friends",
    matches: "Matches",
    
    // About page
    aboutOloo: "About Òloo",
    culturedConnection: "Cultured in Connection",
    aboutDesc: "Òloo is a premium dating platform designed to celebrate African culture while fostering meaningful connections across the diaspora.",
    ourMission: "Our Mission",
    missionDesc: "We believe in bringing people together through shared values, cultural appreciation, and authentic connections. Òloo provides a safe, secure, and culturally-rich environment for individuals to find meaningful relationships.",
    whatMakesDifferent: "What Makes Us Different",
    culturalCelebration: "Cultural celebration at the heart of every connection",
    advancedVerification: "Advanced verification systems for safety and authenticity",
    premiumFeatures: "Premium features designed for meaningful relationships",
    communityFocused: "Community-focused platform with real-time connections",
    contactUs: "Contact Us",
    contactDesc: "Have questions or feedback? We'd love to hear from you at",
    
    // Premium page
    upgradeYourLoveLife: "Upgrade Your Love Life",
    premiumDesc: "Unlock premium features and find meaningful connections with people who share your cultural values",
    mostPopular: "Most Popular",
    silver: "Silver",
    gold: "Gold",
    platinum: "Platinum",
    perMonth: "/month",
    enhancedDating: "Enhanced dating experience",
    premiumCultural: "Premium cultural connections",
    eliteDating: "Elite dating experience",
    unlimitedLikes: "Unlimited likes",
    seeWhoLikedYou: "See who liked you",
    superLikesPerDay: "Super Likes per day",
    boostPerMonth: "Boost per month",
    noAds: "No ads",
    everythingInSilver: "Everything in Silver",
    unlimitedSuperLikes: "Unlimited Super Likes",
    boostsPerMonth: "Boosts per month",
    priorityLikes: "Priority likes",
    readReceipts: "Read receipts",
    culturalMatchFilter: "Cultural match filter",
    everythingInGold: "Everything in Gold",
    unlimitedBoosts: "Unlimited Boosts",
    messageBeforeMatching: "Message before matching",
    prioritySupport: "Priority customer support",
    exclusiveEvents: "Exclusive events access",
    advancedFilters: "Advanced filters",
    choose: "Choose",
    neverRunOut: "Never run out of chances to connect",
    noMoreGuessing: "No more guessing - see your admirers",
    superBoosts: "Super Boosts",
    getMoreViews: "Get 10x more profile views",
    culturalFilters: "Cultural Filters",
    findSharedHeritage: "Find matches who share your heritage",
    faq: "Frequently Asked Questions",
    canCancelAnytime: "Can I cancel anytime?",
    cancelDesc: "Yes, you can cancel your subscription at any time. No questions asked.",
    paymentsSecure: "Are payments secure?",
    paymentsSecureDesc: "Absolutely. We use industry-standard encryption to protect your payment information.",
    
    // Profile page
    profile: "Profile",
    editProfile: "Edit Profile",
    settings: "Settings",
    tokens: "Tokens",
    stats: "Stats",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    displayName: "Display Name",
    bio: "Bio",
    occupation: "Occupation",
    education: "Education",
    interests: "Interests",
    relationshipGoals: "Relationship Goals",
    age: "Age",
    verificationStatus: "Verification Status",
    accountSettings: "Account Settings",
    privacySettings: "Privacy Settings",
    notificationSettings: "Notification Settings",
    
    // Discover page
    loading: "Loading...",
    noMoreProfiles: "No more profiles",
    loadMore: "Load More",
    viewProfile: "View Profile",
    addFriend: "Add Friend",
    sendMessage: "Send Message",
    superLike: "Super Like",
    like: "Like",
    pass: "Pass",
    undo: "Undo",
    boost: "Boost",
  },
  sw: {
    tagline: "Tunavyounganishwa na Utamaduni",
    createAccount: "Unda akaunti",
    alreadyMember: "Tayari ni mwanachama? Ingia",
    culture: "Utamaduni",
    discover: "Gundua",
    collective: "Pamoja",
    languages: "Lugha",
    signIn: "Ingia",
    joinNow: "Jiunge Sasa",
    back: "Rudi",
    welcomeBack: "Karibu tena",
    email: "Barua pepe",
    password: "Nenosiri",
    location: "Mahali",
    messages: "Ujumbe",
    liveStream: "Mباشر ya Moja kwa Moja",
    premium: "Bora",
    friends: "Marafiki",
    matches: "Mechi",
    profile: "Wasifu",
    settings: "Mipangilio",
    aboutOloo: "Kuhusu Òloo",
    ourMission: "Dhamira Yetu",
    contactUs: "Wasiliana Nasi",
    loading: "Inapakia...",
    like: "Penda",
    superLike: "Penda Sana",
  },
  yo: {
    tagline: "A fi Àṣà Ṣe Ìsopọ̀",
    createAccount: "Ṣẹda àkáùntì",
    alreadyMember: "Ṣe o ti jẹ́ ọmọ ẹgbẹ́? Wọlé",
    culture: "Àṣà",
    discover: "Ṣàwárí",
    collective: "Àjọpọ̀",
    languages: "Àwọn èdè",
    signIn: "Wọlé",
    joinNow: "Darapọ̀ Nísinsin yìí",
    back: "Padà",
    welcomeBack: "Káàbọ̀ padà",
    email: "Ímeèlì",
    password: "Ọ̀rọ̀ ìpamọ́",
    location: "Ìbùdó",
    messages: "Àwọn ìfiráńṣẹ́",
    friends: "Àwọn ọ̀rẹ́",
    profile: "Profaili",
    aboutOloo: "Nípa Òloo",
    loading: "Ń ṣe ìgbéjáde...",
    like: "Fẹ́ràn",
  },
  zu: {
    tagline: "Sihlanganiswa Ngamasiko",
    createAccount: "Dala i-akhawunti",
    alreadyMember: "Usuyilungu? Ngena ngemvume",
    culture: "Amasiko",
    discover: "Thola",
    collective: "Sibumbene",
    languages: "Izilimi",
    signIn: "Ngena",
    joinNow: "Joyina Manje",
    back: "Buyela emuva",
    welcomeBack: "Siyakwamukela futhi",
    email: "I-imeyili",
    password: "Iphasiwedi",
    location: "Indawo",
    messages: "Imilayezo",
    friends: "Abangane",
    profile: "Iphrofayela",
    loading: "Iyalayisha...",
    like: "Uyathanda",
  },
  am: {
    tagline: "በባህል የተገናኘን",
    createAccount: "መለያ ፍጠር",
    alreadyMember: "ቀድሞውኑ አባል ነዎት? ግባ",
    culture: "ባህል",
    discover: "አግኝ",
    collective: "አንድነት",
    languages: "ቋንቋዎች",
    signIn: "ግባ",
    joinNow: "አሁን ተቀላቀል",
    back: "ተመለስ",
    welcomeBack: "እንኳን ደህና መጡ",
    email: "ኢሜይል",
    password: "የይለፍ ቃል",
    location: "አድራሻ",
    messages: "መልዕክቶች",
    friends: "ጓደኞች",
    profile: "መገለጫ",
    loading: "በመጫን ላይ...",
    like: "ይወዱ",
  },
  ha: {
    tagline: "An Haɗa Mu Ta Al'ada",
    createAccount: "Ƙirƙiri asusun",
    alreadyMember: "Kai memba ne? Shiga",
    culture: "Al'ada",
    discover: "Gano",
    collective: "Tare",
    languages: "Harsuna",
    signIn: "Shiga",
    joinNow: "Shiga Yanzu",
    back: "Koma",
    welcomeBack: "Maraba da dawowa",
    email: "Imel",
    password: "Kalmar sirri",
    location: "Wuri",
    messages: "Saƙonni",
    friends: "Abokai",
    profile: "Bayanan",
    loading: "Ana lodawa...",
    like: "So",
  },
  ig: {
    tagline: "Ejikọtara N'omenala",
    createAccount: "Mepụta akaụntụ",
    alreadyMember: "Ị bụlarị onye òtù? Banye",
    culture: "Omenala",
    discover: "Chọpụta",
    collective: "Ọnụ",
    languages: "Asụsụ",
    signIn: "Banye",
    joinNow: "Sonye Ugbu a",
    back: "Laghachi azụ",
    welcomeBack: "Nnọọ ọzọ",
    email: "Email",
    password: "Okwuntụghe",
    location: "Ebe",
    messages: "Ozi",
    friends: "Ndị enyi",
    profile: "Profaịlụ",
    loading: "Na-ebugo...",
    like: "Masị",
  },
  // Adding other languages with at least key translations
  so: { tagline: "Dhaqan ku Xidhan", createAccount: "Samee koonto", culture: "Dhaqan", languages: "Luqadaha" },
  om: { tagline: "Aadaa Waliin Walitti Dhufeenya", createAccount: "Akkaawuntii Uumi", culture: "Aadaa", languages: "Afaanota" },
  sn: { tagline: "Takabatana Netsika", createAccount: "Gadzira account", culture: "Tsika", languages: "Mitauro" },
  wo: { tagline: "Yoon Na Ci Aadaa", createAccount: "Sos konte", culture: "Aadaa", languages: "Làkk" },
  xh: { tagline: "Sidibene Ngenkcubeko", createAccount: "Yenza i-akhawunti", culture: "Inkcubeko", languages: "Iilwimi" },
  ti: { tagline: "ብባህሊ ተራኺብና", createAccount: "ኣካውንት ፍጠር", culture: "ባህሊ", languages: "ቋንቋታት" },
  af: { tagline: "Kultuurlik Verbind", createAccount: "Skep rekening", culture: "Kultuur", languages: "Tale" },
  ak: { tagline: "Amanneɛ Mu Nkitahodie", createAccount: "Yɛ akontaabu", culture: "Amanneɛ", languages: "Kasa" },
  rw: { tagline: "Duhujwe n'Umuco", createAccount: "Kora konti", culture: "Umuco", languages: "Indimi" },
  ln: { tagline: "Tokutani na Mimeseno", createAccount: "Kela kɔnti", culture: "Mimeseno", languages: "Nkótá" },
  ff: { tagline: "Jokkondiranɗe e Golle", createAccount: "Sos konte", culture: "Golle", languages: "Ɗemɗe" },
  bem: { tagline: "Twabungana mu Micila", createAccount: "Panga akawunti", culture: "Micila", languages: "Imilaka" },
  tn: { tagline: "Re Kopane ka Setso", createAccount: "Tlhama akhaonto", culture: "Setso", languages: "Maleme" },
  tw: { tagline: "Amammerɛ Mu Nkabom", createAccount: "Yɛ akontaabu", culture: "Amammerɛ", languages: "Kasa" },
};
