-- Add account settings columns to profiles table
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS show_profile BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS allow_messages BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS show_online_status BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS open_to_kids BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS want_kids BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS have_kids BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS notify_matches BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS notify_messages BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS notify_streams BOOLEAN DEFAULT true;